// Module included in the following assemblies:
//
// * installing/installing_bare_metal/installing-bare-metal.adoc
// * installing/installing_restricted_networks/installing-restricted-networks-bare-metal.adoc
// * installing/installing_restricted_networks/installing-restricted-networks-vsphere.adoc
// * installing/installing_vsphere/installing-vsphere.adoc

[id="installation-requirements-user-infra_{context}"]
= Machine requirements for a cluster with user-provisioned infrastructure

For a cluster that contains user-provisioned infrastructure, you must deploy all
of the required machines.

[id="machine-requirements_{context}"]
== Required machines

The smallest {product-title} clusters require the following machines:

* One temporary bootstrap machine

* Three control plane, or master, machines

* At least two compute, or worker, machines

[NOTE]
====
The cluster requires the bootstrap machine to deploy the {product-title} cluster
on the three control plane machines. You can remove the bootstrap machine after
you install the cluster.
====

[IMPORTANT]
====
To improve high availability of your cluster, distribute the control plane machines over different z/VM instances. These can, but need not run on the same Z or LinuxONE hardware.
====

The bootstrap and control plane machines must use {op-system-first} as the
operating system.

[id="network-connectivity_{context}"]
== Network connectivity requirements

All the {op-system-first} machines require network in `initramfs` during boot
to fetch Ignition config files from the Machine Config Server. The machines are configured with static IP
addresses. No DHCP server is required.

== IBM Z network connectivity requirements

To install on IBM Z under z/VM, you require a single z/VM virtual NIC in layer 2 mode. You also need:

*   A direct-attached OSA or RoCE network adapter
*   A z/VM VSwitch set up (for a preferred setup, use OSA link aggregation)

[id="minimum-resource-requirements_{context}"]
== Minimum resource requirements

Each cluster machine must meet the following minimum requirements:

[cols="2,2,2,2,2",options="header"]
|===

|Machine
|Operating System
|vCPU
|RAM
|Storage

|Bootstrap
|{op-system}
|4
|16 GB
|120 GB

|Control plane
|{op-system}
|4
|16 GB
|120 GB

|Compute
|{op-system} or RHEL 7.6
|2
|8 GB
|120 GB

|===

== Minimum IBM Z system requirements

You can install OpenShift 4.2 on IBM Z hardware as of z13, z13s or LinuxONE.

=== Hardware requirements
*     1 LPAR with 3 IFLs that supports SMT2
*     1 OSA or RoCE network adapter, or both

=== Operating system requirements

*     One instance of z/VM 7.1

On your z/VM instance, set up:

* 3 guest virtual machines for OCP control plane machines (master nodes)
* 3 guest virtual mchines  for OCP compute machines (worker nodes)
* 1 guest virtual machine for the temporary OCP bootstrap machine

=== Disk storage for the z/VM guest virtual machines 

*     FICON attached disk storage (DASDs). These can be z/VM minidisks, fullpack minidisks, or dedicated DASDs. If available, use HyperPAV to ensure optimal performance.
*     FCP attached disk storage

=== Storage / Main Memory

*   16 GB for OCP control plane machines (master nodes)
*   8 GB for OCP compute machines (worker nodes)
*   16 GB for the temporary OCP bootstrap machine

== Preferred IBM Z system requirements

=== Hardware requirements
*     3 LPARs with 6 IFLs that support SMT2
*     1 or 2 OSA or RoCE network adapters, or both

=== Operating system requirements

*   2 or 3 instances of z/VM 7.1 for high availability

On your z/VM instances, set up:

*   3 guest virtual machines for OCP control plane machines, one per z/VM instance
*   At least 6 guest virtual mchines for OCP compute machines, distributed across the z/VM instances
*   1 guest virtual machine for the temporary OCP bootstrap machine

=== Disk storage for the z/VM guest virtual machines 

*   FICON attached disk storage (DASDs). These can be z/VM minidisks, fullpack minidisks, or dedicated DASDs. If available, use HyperPAV to ensure optimal performance.
*   FCP attached disk storage

=== Storage / Main Memory

*   16 GB for OCP control plane machines (master nodes)
*   8 GB for OCP compute machines (worker nodes)
*   16 GB for the temporary OCP bootstrap machine


[id="csr_management_{context}"]
== Certificate signing requests management

Because your cluster has limited access to automatic machine management when you
use infrastructure that you provision, you must provide a mechanism for approving
cluster certificate signing requests (CSRs) after installation. The
`kube-controller-manager` only approves the kubelet client CSRs. The
`machine-approver` cannot guarantee the validity of a serving certificate
that is requested by using kubelet credentials because it cannot confirm that
the correct machine issued the request. You must determine and implement a
method of verifying the validity of the kubelet serving certificate requests
and approving them.
